# Generated by Django 3.1.3 on 2020-11-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicationName', models.CharField(default='', max_length=4200, null=True)),
                ('Category', models.CharField(default='', max_length=4200, null=True)),
                ('OverallUserRating', models.CharField(default='', max_length=4200, null=True)),
                ('NumberOfUsersReviews', models.CharField(default='', max_length=4200, null=True)),
                ('Size', models.CharField(default='', max_length=4200, null=True)),
                ('NumberOfUserDownloads', models.CharField(default='', max_length=4200, null=True)),
                ('PaidOrFree', models.CharField(default='', max_length=4200, null=True)),
                ('Price', models.CharField(default='', max_length=4200, null=True)),
                ('AgeGroup', models.CharField(default='', max_length=4200, null=True)),
                ('Genres', models.CharField(default='', max_length=4200, null=True)),
            ],
        ),
    ]
